# Generated by Django 2.2.5 on 2019-09-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
        ('debtor', '0002_debtor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank_account.Account'),
            preserve_default=False,
        ),
    ]
