# Generated by Django 2.2.5 on 2019-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0003_debtor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
