# Generated by Django 2.2.5 on 2019-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('debtor', '0004_auto_20190921_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='invoices',
            field=models.ManyToManyField(to='invoice.Invoice'),
        ),
    ]
