# Generated by Django 2.2.5 on 2019-09-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('debtor', '0005_debtor_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='invoices',
        ),
        migrations.CreateModel(
            name='DebtorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtor.Debtor')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
    ]
