# Generated by Django 2.2.5 on 2019-09-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0006_auto_20190921_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebtorInvoice',
        ),
    ]
