# Generated by Django 2.2.5 on 2019-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'OPEN'), (2, 'PAID'), (3, 'OVERDUE'), (4, 'CANCELED')], default=1)),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
