# Generated by Django 2.2.5 on 2019-09-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0007_delete_debtorinvoice'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='debtor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='debtor.Debtor'),
            preserve_default=False,
        ),
    ]
